# Generated by Django 5.2.5 on 2025-12-29 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorieApp', '0002_initial'),
        ('revenueApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revenue',
            options={'ordering': ['-date'], 'verbose_name': 'Revenu', 'verbose_name_plural': 'Revenus'},
        ),
        migrations.AddField(
            model_name='revenue',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenues', to='categorieApp.categorie', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
