# Generated by Django 5.2.5 on 2025-12-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorieApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='alerte_activee',
            field=models.BooleanField(default=True, verbose_name='Activer les alertes email'),
        ),
    ]
